/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/footer/Footer.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    MBadge: typeof import('./components/MBadge.vue')['default']
    MSwitch: typeof import('./components/MSwitch.vue')['default']
    MTerminal: typeof import('./components/terminal/MTerminal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
